<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="/Includes/style/login.css">
</head>
<body>

<div>
    <form method="POST" action="login.phtml">
        <fieldset>
            <div>
                <label for="username">Username</label>
                <input id="username" name="username" type="text"/>
            </div>

            <div>
                <label for="password">Password</label>
                <input id="password" name="password" type="password"/>
            </div>

            <button type="button">Login</button> <!-- Does not submit for now -->

        </fieldset>
    </form>
</div>

</body>
</html>
